name: Run Kubeflow Pipeline on-prem

on:
  push:
    branches: [main, '*']
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: self-hosted
    steps:
      - name: Force SSH for GitHub
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use system Python
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies
        run: pip install kfp

      - name: Compile pipeline
        run: python3 -m pipelines.compile_pipeline

      - name: Run Kubeflow pipeline trigger script
        run: python3 -m pipelines.run_pipeline