name: Run Kubeflow Pipeline on-prem

on:
  push:
    branches: [main, fix_wf]
  workflow_dispatch:

jobs:
  run_pipeline:
    runs-on: self-hosted
    steps:
      - name: Force SSH for GitHub
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure tool cache
        run: |
          mkdir -p $HOME/actions-toolcache
          echo "RUNNER_TOOL_CACHE=$HOME/actions-toolcache" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install kfp

      - name: Compile pipeline
        run: python pipelines/compile_pipeline.py

      - name: Run Kubeflow pipeline trigger script
        env:
          KFP_HOST: ${{ secrets.KFP_HOST }}
          KFP_AUTH_TOKEN: ${{ secrets.KFP_AUTH_TOKEN }}
        run: python pipelines/run_pipeline.py